# Generated by Django 4.2.3 on 2023-07-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit_api', '0004_albumreview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='image',
            field=models.ImageField(null=True, upload_to='album_covers'),
        ),
    ]
